# Generated by Django 4.1.3 on 2022-11-05 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catergory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 5, 19, 6, 42, 435675, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
