# Generated by Django 4.1.3 on 2022-11-05 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_catergory_add_date_alter_catergory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='image',
            field=models.ImageField(default=2, upload_to='category/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2022, 11, 5, 19, 7, 55, 740405, tzinfo=datetime.timezone.utc), upload_to='post/'),
            preserve_default=False,
        ),
    ]
